spring:
  application:
    name: emilytalks
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_TOKEN}
  expiration: ${JWT_EXPIRATION}

assemblyai:
  api:
    key: ${API_KEY_ASSEMBLY}

deepseek:
  api:
    key: ${API_KEY_DEEPSEEK}

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS}
