name: Java CI with Gradle & SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY_ASSEMBLY: ${{ secrets.API_KEY_ASSEMBLY }}
      API_KEY_DEEPSEEK: ${{ secrets.API_KEY_DEEPSEEK }}
      CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
      JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build, test & coverage
        run: ./gradlew test jacocoTestReport

      - name: Dependency
        run: ./gradlew copyDependencies

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=Natzgun_EmilyTalks
            -Dsonar.organization=4mem
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=.
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.exclusions=src/test/java/**
            -Dsonar.java.libraries=build/libs/*.jar,build/classes/java/main
